-- Create Business Config table
CREATE TABLE IF NOT EXISTS public.business_config (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hero_bg_image TEXT,
  hero_title TEXT,
  hero_subtitle TEXT,
  gallery_images TEXT[] DEFAULT '{}',
  open_time TEXT DEFAULT '09:00',
  close_time TEXT DEFAULT '19:00',
  days_off INTEGER[] DEFAULT '{0}', -- 0 = Sunday
  cancellation_policy TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default config if not exists
INSERT INTO public.business_config (id, hero_bg_image, hero_title, hero_subtitle, open_time, close_time, days_off)
VALUES (
  1, 
  '/images/hero-barber.jpg', 
  'A arte do corte', 
  'perfeito', 
  '09:00', 
  '19:00', 
  '{0}'
) ON CONFLICT (id) DO NOTHING;

-- Create Barbers table
CREATE TABLE IF NOT EXISTS public.barbers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  specialties TEXT[] DEFAULT '{}',
  image_url TEXT,
  instagram TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default barbers
INSERT INTO public.barbers (name, role, specialties, image_url)
VALUES 
  ('Carlos Silva', 'Barbeiro / Especialista em Corte & Barba', '{"Corte Masculino", "Barba", "Pigmentacao"}', '/images/barber-carlos.jpg'),
  ('Rafael Costa', 'Barbeiro / Especialista em Tratamentos', '{"Corte Masculino", "Sobrancelha", "Nevou"}', '/images/barber-rafael.jpg');

-- Create Products table (if not exists, or update it)
CREATE TABLE IF NOT EXISTS public.products (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL,
  stock INTEGER DEFAULT 0,
  image_url TEXT,
  category_id UUID, -- Optional
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default products
INSERT INTO public.products (name, description, price, stock, image_url)
VALUES 
  ('Pomada Modeladora', 'FixaÃ§Ã£o forte e efeito matte', 35.00, 20, 'https://images.unsplash.com/photo-1626307416562-ee839676f5fc?w=300&h=300&fit=crop'),
  ('Ã“leo para Barba', 'HidrataÃ§Ã£o e brilho para sua barba', 25.00, 15, 'https://images.unsplash.com/photo-1626307416562-ee839676f5fc?w=300&h=300&fit=crop'),
  ('Shampoo 2 em 1', 'Cabelo e barba', 30.00, 12, NULL);

-- Enable RLS (Row Level Security) - Optional but good practice
-- For now, we allow public read/write to allow the app to work without auth for simple demo purposes, 
-- or we can rely on the service role if we had one, but the client uses anon key.
-- We will enable public access for simplicity as requested by the user flow ("admin123" hardcoded password).

ALTER TABLE public.business_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read/write for all" ON public.business_config FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.barbers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read/write for all" ON public.barbers FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read/write for all" ON public.products FOR ALL USING (true) WITH CHECK (true);


CREATE TABLE IF NOT EXISTS public.services (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  duration_min INTEGER NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  visible BOOLEAN DEFAULT true,
  category TEXT DEFAULT 'Geral',
  type TEXT DEFAULT 'barbearia',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.plans (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  period TEXT DEFAULT '/mes',
  description TEXT,
  features TEXT[] DEFAULT '{}',
  discount_percent INTEGER,
  visible BOOLEAN DEFAULT true,
  featured BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.appointments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  barber_id UUID,
  service_id UUID,
  service_ids UUID[] DEFAULT '{}',
  products JSONB DEFAULT '[]',
  start_at TIMESTAMP WITH TIME ZONE NOT NULL,
  end_at TIMESTAMP WITH TIME ZONE NOT NULL,
  status TEXT DEFAULT 'PENDENTE',
  price NUMERIC(10, 2) DEFAULT 0,
  paid_amount NUMERIC(10, 2) DEFAULT 0,
  payment_method TEXT,
  notes TEXT,
  custom_price NUMERIC(10, 2),
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.customer_plans (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  plan_id UUID,
  start_date TIMESTAMP WITH TIME ZONE NOT NULL,
  active BOOLEAN DEFAULT true,
  status TEXT DEFAULT 'active',
  usage_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.expenses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  description TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  date TIMESTAMP WITH TIME ZONE NOT NULL,
  category TEXT,
  payment_method TEXT,
  is_recurring BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add is_active column to barbers table
ALTER TABLE public.barbers ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;

-- Add tags array to customers table
ALTER TABLE customers ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';

-- Add customer_tags JSONB array to business_config
ALTER TABLE business_config ADD COLUMN IF NOT EXISTS customer_tags JSONB DEFAULT '[]';

-- Tell PostgREST to reload the schema cache so the new columns are available via the API
NOTIFY pgrst, 'reload schema';

-- Add default commission columns to business_config table
ALTER TABLE public.business_config 
ADD COLUMN IF NOT EXISTS default_service_commission_percent INTEGER DEFAULT 40,
ADD COLUMN IF NOT EXISTS default_product_commission_percent INTEGER DEFAULT 10;

-- Adiciona coluna para pÃ¡ginas permitidas ao operacional
ALTER TABLE business_config 
ADD COLUMN IF NOT EXISTS allowed_operational_pages TEXT[] DEFAULT ARRAY['Agenda'];

-- Garante que o valor inicial seja o padrÃ£o caso a coluna jÃ¡ exista mas esteja nula
UPDATE business_config SET allowed_operational_pages = ARRAY['Agenda'] WHERE allowed_operational_pages IS NULL;

-- Add professional commission percentage to plans table
ALTER TABLE public.plans 
ADD COLUMN IF NOT EXISTS professional_commission_percent INTEGER DEFAULT 40;

-- Comment on column
COMMENT ON COLUMN public.plans.professional_commission_percent IS 'Percentage of plan value that goes to the professional (0-100). Default 40.';

-- Add commissioned column to products table
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS commissioned BOOLEAN DEFAULT TRUE;

-- Update existing products to have commissioned = true (optional, as default covers new inserts, but good for clarity)
UPDATE products SET commissioned = TRUE WHERE commissioned IS NULL;

-- Add renews_at column to customer_plans table
ALTER TABLE customer_plans 
ADD COLUMN IF NOT EXISTS renews_at TIMESTAMP WITH TIME ZONE;

-- Add comment
COMMENT ON COLUMN customer_plans.renews_at IS 'Timestamp when the plan renews or expires';

-- Add 'commission_percent' column to 'services' table custom commission rates
-- Default is NULL (which means "use global default")

ALTER TABLE public.services 
ADD COLUMN IF NOT EXISTS "commission_percent" INTEGER DEFAULT NULL;

-- Grant permissions (standard)
GRANT ALL ON TABLE public.services TO anon;
GRANT ALL ON TABLE public.services TO authenticated;
GRANT ALL ON TABLE public.services TO service_role;

-- Add 'order' column to 'services' table to support custom ordering
-- Default to 0, or we could auto-increment if we wanted, but 0 is fine for now as we will reorder them in UI.
ALTER TABLE public.services 
ADD COLUMN IF NOT EXISTS "order" INTEGER DEFAULT 0;

-- Grant permissions (if needed, though usually covered by table grants)
GRANT ALL ON TABLE public.services TO anon;
GRANT ALL ON TABLE public.services TO authenticated;
GRANT ALL ON TABLE public.services TO service_role;

-- Add status column to customer_plans table
ALTER TABLE customer_plans 
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';

-- Add comment
COMMENT ON COLUMN customer_plans.status IS 'Status of the plan (active, inactive, cancelled)';

-- Optional: Backfill status based on active boolean if it exists
-- UPDATE customer_plans SET status = 'active' WHERE active = true;
-- UPDATE customer_plans SET status = 'inactive' WHERE active = false;

-- Migration to add usage_limit to plans table
ALTER TABLE plans ADD COLUMN IF NOT EXISTS usage_limit INTEGER DEFAULT 1;

-- Update existing plans to have a default limit if needed
UPDATE plans SET usage_limit = 1 WHERE usage_limit IS NULL;

-- Add whatsapp_overdue_template column to business_config table
ALTER TABLE public.business_config ADD COLUMN IF NOT EXISTS whatsapp_overdue_template TEXT DEFAULT 'OlÃ¡ {cliente}! Notamos que faz tempo que vocÃª nÃ£o vem fazer seu {servico}. Que tal agendar um horÃ¡rio?';

-- Create Customers table
CREATE TABLE IF NOT EXISTS public.customers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT UNIQUE NOT NULL,
  birth_date DATE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read/write for all" ON public.customers FOR ALL USING (true) WITH CHECK (true);

-- Create Expense Categories table
CREATE TABLE IF NOT EXISTS public.expense_categories (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default categories
INSERT INTO public.expense_categories (name)
VALUES 
  ('Produtos (ReposiÃ§Ã£o)'),
  ('ServiÃ§o (ManutenÃ§Ã£o)'),
  ('Contas (Luz/Ãgua)'),
  ('ComissÃ£o (Avulsa)'),
  ('Outros')
ON CONFLICT (name) DO NOTHING;

-- Enable RLS
ALTER TABLE public.expense_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read/write for all" ON public.expense_categories FOR ALL USING (true) WITH CHECK (true);

-- Insert default operational user
insert into users (name, email, password, role)
values ('Operacional', 'operacional@triv.com', 'operacional123', 'OPERATIONAL')
on conflict (email) do nothing;

-- Create users table
create table if not exists users (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  email text not null unique,
  password text not null, -- Plain text for now as per request/simplicity, hash later if needed
  role text not null check (role in ('ADMIN', 'OPERATIONAL')),
  created_at timestamp with time zone default now()
);

-- Insert default admin user if not exists
insert into users (name, email, password, role)
values ('Administrador', 'admin@triv.com', 'admin123', 'ADMIN')
on conflict (email) do nothing;

-- Sync status column with the legacy active boolean column
-- This fixes the issue where inactive plans became 'active' due to the default value of the new column

UPDATE customer_plans 
SET status = 'inactive' 
WHERE active = false;

UPDATE customer_plans 
SET status = 'active' 
WHERE active = true AND status IS NULL; 
-- (The default 'active' likely handled the second case, but safety first)

-- Add missing whatsapp_overdue_template column
ALTER TABLE business_config ADD COLUMN IF NOT EXISTS whatsapp_overdue_template TEXT;

-- Reload schema cache
NOTIFY pgrst, 'reload schema';


